spring:
  config:
    activate:
      on-profile: proxy

    # DB Configuration
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.45.135:3360/rtdbc?useSSL=false
    username: test
    password: test12!@


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none #create, update
    defer-datasource-initialization: false
  sql:
    init:
      mode: never #always