spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.45.135:3360/multi_dev?useSSL=false
    username: develop
    password: develop12!@


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update #create, update
    defer-datasource-initialization: false
  sql:
    init:
      mode: never #always